In [ ]:
Name:Swaroop Naik Roll:23102A0001

In [2]:
x <- c(2, 3, 5, 7)
x

[1] 2 3 5 7

In [3]:
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

In [4]:
c(2,3,5,7) + c(-2,-3,-5,8)

[1]  0  0  0 15

In [5]:
c(2,3,5,7) - c(-2,-3,-5,8)

[1]  4  6 10 -1

In [6]:
c(2,3,5,7) * c(-2,-3,-5,8)

[1]  -4  -9 -25  56

In [7]:
c(2,3,5,7) / c(-2,-3,-5,8)

[1] -1.000 -1.000 -1.000  0.875

In [8]:
2^3
2^0.5
2^-0.5

c(2,3,5,7)^2
c(2,3,5,7)^c(2,3)

[1] 8

[1] 1.414214

[1] 0.7071068

[1]  4  9 25 49

[1]   4  27  25 343

In [9]:
2 %/% 2
5 %/% 2
7 %/% 3

c(2,3,5,7) %/% 2
c(2,3,5,7) %/% c(2,3)

[1] 1

[1] 2

[1] 2

[1] 1 1 2 3

[1] 1 1 2 2

In [10]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

c(2,3,5,7) %% 2
c(2,3,5,7) %% c(2,3)

[1] 0

[1] 1

[1] 1

[1] 3

[1] 0 1 1 1

[1] 0 0 1 1

In [11]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

In [12]:
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8

[1] -7.8

In [13]:
mean(c(2,3,4))

[1] 3

In [14]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

In [15]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

In [16]:
sum(c(2,3,5,7))

[1] 17

In [17]:
prod(c(2,3,5,7))

[1] 210

In [18]:
round(1.23)
round(1.83)
floor(1.83)
ceiling(1.23)

[1] 1

[1] 2

[1] 1

[1] 2

In [20]:
log(10)
log(exp(1))
log(c(10,100,1000))

log10(10)
log10(100)
log10(c(10,100,1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

[1] 1

[1] 2

[1] 1 2 3

In [21]:
exp(1)
exp(2)

[1] 2.718282

[1] 7.389056

In [22]:
x1 <- c(1,2,3,4)
x1

x2 <- x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [23]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1,2,3,4,5,6,7,8)
)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [24]:
x[3,2]

# 21. Row-wise matrix
y <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1,2,3,4,5,6,7,8),
  byrow = TRUE
)

y

[1] 7

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [25]:
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

In [26]:
is.matrix(x)
is.matrix(y)

[1] TRUE

[1] TRUE